### PR TITLE
Add JWT support for user verification

### PR DESCRIPTION
**Pull request by shepherd-06**
Summary

- Logging in to generate a token.
- Accessing protected routes with and without a valid token.
- Logging out to clear the token and then trying to access protected routes.

This PR/branch is created from the `feature/add-authentication` branch. Instead of merging to `development` directly, it will merge to `feature/add-authentication` first. @shepherd-06 will create a separate PR request to merge this branch into `development` when reviewed.

-------------------- 

Changes:

1. JWT Setup:
- Installed necessary packages: express-jwt, jsonwebtoken, and cookie-parser.
- Configured JWT with the secret key sourced from environment variables.

2. Authentication API:
- Implemented the login endpoint which generates and sends a JWT in a cookie upon successful user validation.
- Created a logout endpoint that clears the JWT cookie, effectively logging out the user.

3. Middlewares:
- Introduced authenticateJWT middleware to validate and decode JWT tokens for protected routes.
- Implemented attachUserData middleware to attach user details from the JWT payload to the request object for easy access in route handlers.
- Added error-handling middleware to capture and handle UnauthorizedError, providing informative feedback for cases like invalid or expired tokens.

4. JWT Utility Functions:
- Created generateToken utility function to generate JWTs with user-specific payloads.
- Developed verifyToken utility function to verify and decode JWTs.

5. Cookie Parser:
- Integrated cookie-parser middleware to enable reading JWT tokens from cookies.

### CODE REVIEW

**Comment by shepherd-06** [comment]
> > Hey @vilbedawg the middleware `authenticateJWT.ts` uses the expressjwt's middleware to handle invalid tokens. I have written the same function just in case, but expressjwt handle token verification underneath.
> > image
> > I use `http-only` cookie for both token and refresh-token. `token` has validity of 1h, and `refresh-token` comes with 7d validity. When a token becomes invalid, the front-end will send a refresh token request to the API that hasn't been pushed yet.
> 
> Is the refresh token stored somewhere, assuming they are revocable?

not yet. but I was wondering about it. I will store them in the db when we issuing them, both access and refresh with the associated user.

**Comment by vilbedawg** [comment]
> > > Hey @vilbedawg the middleware `authenticateJWT.ts` uses the expressjwt's middleware to handle invalid tokens. I have written the same function just in case, but expressjwt handle token verification underneath.
> > > image
> > > I use `http-only` cookie for both token and refresh-token. `token` has validity of 1h, and `refresh-token` comes with 7d validity. When a token becomes invalid, the front-end will send a refresh token request to the API that hasn't been pushed yet.
> > 
> > 
> > Is the refresh token stored somewhere, assuming they are revocable?
> 
> not yet. but I was wondering about it. I will store them in the db when we issuing them, both access and refresh with the associated user, in next PR.

Access tokens are typically short-lived (e.g., 15-60 minutes) and should be stored securely on the client side, typically in an HTTP-only cookie. There's no need to store them in a database. You can just obtain a new access token using the refresh token that is persisted in the database.

**Comment by shepherd-06** [comment]
> > > > Hey @vilbedawg the middleware `authenticateJWT.ts` uses the expressjwt's middleware to handle invalid tokens. I have written the same function just in case, but expressjwt handle token verification underneath.
> > > > image
> > > > I use `http-only` cookie for both token and refresh-token. `token` has validity of 1h, and `refresh-token` comes with 7d validity. When a token becomes invalid, the front-end will send a refresh token request to the API that hasn't been pushed yet.
> > > 
> > > 
> > > Is the refresh token stored somewhere, assuming they are revocable?
> > 
> > 
> > not yet. but I was wondering about it. I will store them in the db when we issuing them, both access and refresh with the associated user, in next PR.
> 
> Access tokens are typically short-lived (e.g., 15-60 minutes) and should be stored securely on the client side, typically in an HTTP-only cookie. There's no need to store them in a database. You can just obtain a new access token using the refresh token that is persisted in the database.

yeah current format sends both access and refresh in http-only mode. I can just reduce the time frame for access token to 15m and store the refresh tokens on DB against userID.

**Comment by shepherd-06** [comment]
@vilbedawg I have changed the token expiry to 15m from 1h. Refresh Token related works are on a separate PR. I will work on it later.

**Comment by vilbedawg** [comment]
Majority of these changes have been added in a separate [PR](https://github.com/Koodikukkaro/Kendo-tournament-app/pull/27).

**Pull request closed without merging**
